### ISSUE TITLE
Doesn't support updating certain checksum types

### ISSUE THREAD

**Issue by amagura** [juergenhoetzel/pkgbuild-mode#10]
Presently, pkgbuild-mode doesn't support sha1sums, sha256sums, or the less common alternatives to sha256sums, such as sha384sums, sha224sums, and sha512sums.  

Could support for _at least_ sha1sums and sha256sums please be added?

**Comment by juergenhoetzel** [comment]
`pkgbuild-mode` relies on `makepkg -g` to update the sums. So if you add

```
INTEGRITY_CHECK=(sha1 sha256 sha384 sha512)
```

to your `~.makepkg.conf` it will generated the corresponding sums

**Comment by juergenhoetzel** [comment]
See #9
