### ISSUE TITLE
support updpkgsums command

### ISSUE THREAD

**Issue by blaenk** [juergenhoetzel/pkgbuild-mode#13]
This command [automatically updates checksums](https://wiki.archlinux.org/index.php/Makepkg#Generate_new_checksums), which might make the implementation of this functionality much easier.

**Comment by juergenhoetzel** [comment]
```updpkgsums``` rewrites  an existing PKGBUILD file. ````pkgbuild-update-sums-line' ``` needs to handle a potentially modified buffer. I don't see how I could simplify the current implementation.

**Comment by blaenk** [comment]
Ah fair enough.
