### ISSUE TITLE
md5 should be replaced

### ISSUE THREAD

**Issue by bricewge** [juergenhoetzel/pkgbuild-mode#9]
`md5` is known be vulnarable to collisions it should be replace by `sha256sums` or similar.
Have a look on the [wiki](https://wiki.archlinux.org/index.php/PKGBUILD#Integrity_variables) for more information.

**Comment by juergenhoetzel** [comment]
pkgbuild-mode just uses `makepkg -g` to generate the sums-line.

Thus  only generates md5, if configured so in /etc/makepkg.conf or ~/makepkg.conf.
